FORMAT: 1A
HOST: https://errnd.herokuapp.com/api/v1

# Errnd

Errnd is a platform where your errands are completed by your communities

#### Features 

  * Users can create an account and log in
  * Users can create a profile and view their profile or others profile
  * Users can switch thier role from runner to customer and vice versa
  * Users can create and update services


## Welcome Page [/]

### Welcome a user [GET]

  * Helps to welcome a user to the API
  
+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Location: /

    + Body        
    
    
            {
                "status": 200,
                "data": {
                    "message": "Welcome to Errnd API, A platform where your errands are completed by your communities"
                }
            }

## Sign up [/auth/signup]

### Sign up  a user [POST]

  * Helps a user to sign up on the API
  
+ Request (application/json)

        {
            "role": "runner",
            "email": "newuser@email.com",
            "password": "password",
            "username": "newuser"
        }

+ Response 201 (application/json)

    + Headers

            Location: /auth/signup

    + Body        
    
            {
                "status": 201,
                "data": {
                    "message": "User created successfully",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1c3RvbWVyNDAwMEBjdXN0b21lci5jb20iLCJ1c2VySWQiOjUsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTU1OTE0ODI3NSwiZXhwIjoxNTU5MjM0Njc1fQ.E0sQef1pYjYI0B0v6IDokrwiW-2XF1ADJE4ddy2bqJ0"
                }
            }
            
              
        
+ Response 409 (application/json)

    + Headers

            Location: /auth/signup

    + Body        
    
            {
                "status": 409,
                "data": {
                    "error": "User already exists, please sign up a new user"
                }
            }
            
+ Response 400 (application/json)

    + Headers

            Location: /auth/signup

    + Body        
    
            {
                "status": 400,
                "data": {
                    "error": {
                        "email": "Invalid email"
                    }
                }
            }

    
            {
                "status": 400,
                "data": {
                    "error": "role must be runner or customer"
                }
            }         
      

## Signin [/auth/login]

### Login a user [POST]

  * Helps a user to use all features of the API
  
+ Request (application/json)

        {
                "email": "newuser@email.com",
                "password": "password"
        }

+ Response 200 (application/json)

    + Headers

            Location: /auth/login

    + Body        
    
    
            {
                "status": 200,
                "data": {
                    "message": "Welcome newuser",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImN1c3RvbWVyNDAwMEBjdXN0b21lci5jb20iLCJ1c2VySWQiOjUsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTU1OTE0ODM4MywiZXhwIjoxNTU5MjM0NzgzfQ.Y6Uao5otns3NJSWwGo-XgOwW8PTckVlu1QPgJ11UN04"
                }
            }
       
+ Response 401 (application/json)

    + Headers

            Location: /auth/login

    + Body        
    
            {
                status: 401,
                data: {
                    message: 'Invalid email/username or password',
                }
            }

+ Response 404 (application/json)

    + Headers

            Location: /auth/login

    + Body        
    
            {
                status: 404,
                data: {
                    error: 'User not found, please register user onto the platform',
                }
            }
            
+ Response 400 (application/json)

    + Headers

            Location: /auth/login

    + Body        
    
            {
                "status": 400,
                "data": {
                    "error": {
                        emailOrUsername: 'email or username must be filled',
                        password: 'password must be filled',
                    }
                }
            }

            {
                "status": 400,
                "data": {
                    "error": {
                        email: 'Invalid email'
                    }
                }
                
## Profile [/profile/{username}]
+ Parameters
    + username (text) - johndolly

### Create user's profile [POST]

  * Helps a user to populate his profile after signing up onto the platform
  
+ Request

    + Body
    
            {
                "firstName": "John",
                "lastName": "Dolly",
                "image": "https://images.unsplash.com/photo-1497551060073-4c5ab6435f12?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80",
                "location": "Lagos",
                "bio": "I am a sofware engineer",
                "phone": "09099933373"
            }
    
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1bm5lckBydW5uZXIuY29tIiwidXNlcklkIjoxLCJyb2xlIjoiY3VzdG9tZXIiLCJ1c2VybmFtZSI6ImludmFsaWR1c2VyIiwiaWF0IjoxNTU5Mzk2Nzg2LCJleHAiOjE1NTk0ODMxODZ9.0PItRXbVtKezfd6FTLTgEcKYOGd1EY3UVYOLWGcgACo
        

            
+ Response 200 (application/json)

    + Headers

            Location: /profile/johndolly

    + Body        
    
    
            {
                "status": 200,
                "data": {
                    "message": "Users profile created successfully",
                    "profile": {
                        "id": 1,
                        "firstName": "John",
                        "lastName": "Dolly",
                        "phone": "09099933373",
                        "image": "https://images.unsplash.com/photo-1497551060073-4c5ab6435f12?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80",
                        "bio": "I am a sofware engineer",
                        "location": "Lagos",
                        "createdAt": "2019-05-30T21:05:53.725Z",
                        "updatedAt": "2019-06-01T13:42:53.520Z",
                        "userId": 10
                    }
                }
            }
            
+ Response 401 (application/json)

    + Headers

            Location: /auth/johndolly
            
    + Body        
    
            {
                status: 401,
                data: {
                    error: 'Unauthorized, you cannot edit another person's profile',
                }
            }
            
            {
                status: 401,
                data: {
                    error: 'Unauthorized, user not authenticated',
                }
            }

### View a user's profile [GET]

  * Helps a user to get his or other people profile
  
+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Location: /profile/billzuckerberg

    + Body        
    
            {
                "status": 200,
                "data": {
                    "message": "Users profile returned succesfully",
                    "user": {
                        "id": 4,
                        "firstName": "Bill",
                        "lastName": "Zuckerberg",
                        "phone": "09099933323",
                        "image": "https://images.unsplash.com/photo-1497551060073-4c5ab6435f12?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80",
                        "bio": "I am a sofware engineer and ceo",
                        "location": "Lagos",
                        "createdAt": "2019-06-01T13:47:31.063Z",
                        "updatedAt": "2019-06-01T13:47:31.063Z",
                        "role": "customer",
                        "email": "runner@runner.com",
                        "username": "runner"
                    }
                }
            }

+ Response 404 (application/json)

    + Headers

            Location: /profile/unregistereduser

    + Body        
    
            {
                "status": 404,
                "data": {
                    "message": "User's profile not found",
                    "profile": {}
                }
            }

## Role [/role/{username}]
+ Parameters
    + username (text) - johndolly

### Switch user's role [PUT]

  * Helps a user to switch his role from runner to customer and vice versa
  
+ Request

    + Body
    
            {
                "role": "customer"
            }
    
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1bm5lckBydW5uZXIuY29tIiwidXNlcklkIjoxLCJyb2xlIjoiY3VzdG9tZXIiLCJ1c2VybmFtZSI6ImludmFsaWR1c2VyIiwiaWF0IjoxNTU5Mzk2Nzg2LCJleHAiOjE1NTk0ODMxODZ9.0PItRXbVtKezfd6FTLTgEcKYOGd1EY3UVYOLWGcgACo
        

            
+ Response 200 (application/json)

    + Headers

            Location: /role/johndolly

    + Body        
    
    
            {
                "status": 200,
                "data": {
                    "message": "Users role switched succesfully"
                }
            }
        
+ Response 404 (application/json)

    + Headers

            Location: /role/johndolly

    + Body        
    
            {
                "status": 404,
                "data": {
                    "message": "User's profile not found",
                    "profile": {}
                }
            }
                
+ Response 401 (application/json)

    + Headers

            Location: /role/johndolly
            
    + Body        
    
            {
                status: 401,
                data: {
                    error: 'Unauthorized, you cannot switch another person's role'
                }
            }   
              
+ Response 400 (application/json)

    + Headers

            Location: /role/johndolly

    + Body        
    
            {
                "status": 400,
                "data": {
                    "error": "role must be runner or customer"
                }
            }
            
            
## Create a Service [/services/{username}]
+ Parameters
    + username (text) - johndolly

### A runner can create a service [POST]

  * Helps a runner to create a service
  
+ Request

    + Body
    
                {
                     "category": "Computer Science",
                     "subcategory": "Web Development",
                     "title": "Develop your web app", 
                     "description": "I can develop your web app using express,react and react native following TDD and Agile",
                     "price": 3500,
                     "days": 3,
                     "media": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
                     "packageoptions": [{
                        "serviceA": "add map to the web app",
                        "quantity": 1,
                        "type": "basic",
                        "price": 2500
                     },
                    {
                     "serviceB": "add timer to the web app",
                     "quantity": 1,
                     "type": "basic",
                     "price": 1000
                    }]
                }

    
    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1bm5lckBydW5uZXIuY29tIiwidXNlcklkIjoxLCJyb2xlIjoiY3VzdG9tZXIiLCJ1c2VybmFtZSI6ImludmFsaWR1c2VyIiwiaWF0IjoxNTU5Mzk2Nzg2LCJleHAiOjE1NTk0ODMxODZ9.0PItRXbVtKezfd6FTLTgEcKYOGd1EY3UVYOLWGcgACo
        

            
+ Response 200 (application/json)

    + Headers

            Location: /services/johndolly

    + Body        
    
    
            {
                "status": 201,
                "data": {
                    "message": "Service created successfully",
                    "service": {
                        "id": 1,
                        "category": "Computer Science",
                        "subcategory": "Web Development",
                        "title": "Develop your web app",
                        "description": "I can develop your web app using express,react and react native following TDD and Agile",
                        "price": 3500,
                        "days": 3,
                        "media": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
                        "packageoptions": [
                            {
                                "serviceA": "add map to the web app",
                                "quantity": 1,
                                "type": "basic",
                                "price": 2500
                            },
                            {
                                "serviceB": "add timer to the web app",
                                "quantity": 1,
                                "type": "basic",
                                "price": 1000
                            }
                        ],
                        "userId": 1,
                        "updatedAt": "2019-06-06T12:49:06.704Z",
                        "createdAt": "2019-06-06T12:49:06.704Z"
                    }
                }
            }
            
+ Response 401 (application/json)

    + Headers

            Location: /services/johndolly
            
    + Body        
    
            {
                status: 401,
                data: {
                    error: 'Unauthorized, you cannot create a service on behalf of another user',
                }
            }
            
            {
                status: 401,
                data: {
                    error: 'Unauthorized, user not authenticated',
                }
            }
            
+ Response 400 (application/json)

    + Headers

            Location: /services/johndolly
            
    + Body        
    
            {
                "status": 400,
                "data": {
                    "error": {
                        "price": "price must be a number",
                        "days": ""
                    }
                }
            }
            
            {
                "status": 400,
                "data": {
                    "error": {
                        "category": "category must be filled",
                        "subcategory": "",
                        "title": "",
                        "price": "",
                        "days": ""
                    }
                }
            }  
            
## Update a Service [/services/{username}/update/{serviceId}]
+ Parameters
    + username (text) - johndolly
    + serviceId (number) - 1

### A runner can update a service [POST]

  * Helps a runner to update a service he created
  
+ Request

    + Body
    
               {
                  "category": "Computer Science",
                  "subcategory": "Web Development",
                  "title": "Develop your mobile app",
                  "description": "I can develop your mobile app using Java/android following TDD and Agile",
                  "price": 3500,
                  "days": 1,
                  "media": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
                  "packageoptions": [{
                        "serviceA": "add map to the mobile app",
                        "quantity": 1,
                        "type": "basic",
                        "price": 2500
                     },
                    {
                     "serviceB": "add timer to the mobile app",
                     "quantity": 1,
                     "type": "basic",
                     "price": 1000
                    }]
                }

    + Headers

            Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJ1bm5lckBydW5uZXIuY29tIiwidXNlcklkIjoxLCJyb2xlIjoiY3VzdG9tZXIiLCJ1c2VybmFtZSI6ImludmFsaWR1c2VyIiwiaWF0IjoxNTU5Mzk2Nzg2LCJleHAiOjE1NTk0ODMxODZ9.0PItRXbVtKezfd6FTLTgEcKYOGd1EY3UVYOLWGcgACo
        

            
+ Response 200 (application/json)

    + Headers

            Location: /services/johndolly/update/1

    + Body        
    
    
            {
                "status": 200,
                "data": {
                    "message": "Service updated successfully",
                    "service": {
                        "id": 1,
                        "category": "Computer Science",
                        "subcategory": "Web Development",
                        "title": "Develop your mobile app",
                        "description": "I can develop your mobile app using Java/android following TDD and Agile",
                        "price": 3500,
                        "days": 1,
                        "media": "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80",
                        "packageoptions": [{
                        "serviceA": "add map to the mobile app",
                        "quantity": 1,
                        "type": "basic",
                        "price": 2500
                        },
                        {
                         "serviceB": "add timer to the mobile app",
                         "quantity": 1,
                         "type": "basic",
                         "price": 1000
                        }]
                        "createdAt": "2019-06-05T12:46:55.003Z",
                        "updatedAt": "2019-06-05T14:30:06.576Z",
                        "userId": 1
                    }
                }
            }
            
+ Response 401 (application/json)

    + Headers

            Location: /services/johndolly/update/1

            
    + Body        
    
            {
                status: 401,
                data: {
                    error: 'Unauthorized, you cannot update a service on behalf of another user',
                }
            }
            
            {
                status: 401,
                data: {
                    error: 'Unauthorized, user not authenticated',
                }
            }
            
+ Response 404 (application/json)

    + Headers

            Location: /services/johndolly/update/1

            
    + Body        
    
            {
                "status": 404,
                "data": {
                    "message": "Service not found",
                    "service": {}
                }
            }